import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HamburgerMenu from "@/lib/components/navigation/HamburgerMenu";
import { createClient } from "@/lib/supabase/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();
  
  const {
    data: { user },
  } = await supabase.auth.getUser();

  let userProfile = null;
  if (user) {
    const { data: profile, error } = await supabase
      .from("profile")
      .select("nickname, avatar_url")
      .eq("id", user.id)
      .single();
    
    if (error) {
      console.error("Profile fetch error:", error);
    } else {
      // キャッシュバスティングのためタイムスタンプを追加
      userProfile = {
        nickname: profile.nickname,
        avatar_url: profile.avatar_url ? `${profile.avatar_url}?t=${Date.now()}` : null
      };
    }
  }

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <HamburgerMenu 
          nickname={userProfile?.nickname || null}
          avatarUrl={userProfile?.avatar_url || null}
          isLoggedIn={!!user}
        />
        {children}
      </body>
    </html>
  );
}
